pool:
  vmImage: 'VS2017-Win2016'

trigger:
- master

steps:
- powershell: scripts/build.ps1
  displayName: 'Build resume'

- task: PublishBuildArtifacts@1
  displayName: 'Publish deployment artifacts'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/artifacts'
    ArtifactName: artifacts

- task: PublishBuildArtifacts@1
  displayName: 'Publish deployment scripts'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/scripts'
    ArtifactName: scripts

