pool:
  vmImage: 'VS2017-Win2016'

trigger:
- master

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.2.102'

- powershell: |
    dotnet --info
    dotnet tool install -g resume-cli --version 0.2.0
  displayName: 'Install resume-cli tool'

- powershell: scripts/build.ps1
  displayName: 'Validate and build resume'

- powershell: scripts/publish.ps1
  displayName: 'Publish resume'
  env:
      AZURE_STORAGE_CONNECTION_STRING: $(AZURE_STORAGE_CONNECTION_STRING)
