pool:
  vmImage: 'VS2017-Win2016'

trigger:
- master

steps:
- powershell: scripts/build.ps1

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/output'
    ArtifactName: resume
