name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest

    env:
      RESUME_JSON: src/resume.json

    steps:
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Restore Tools
      run: dotnet tool restore

    - name: Validate resume
      run: dotnet resume validate -f ${env:RESUME_JSON}

    - name: Build resume
      run: |
        dotnet resume build -f ${env:RESUME_JSON}
        cp artifacts/resume.html artifacts/index.html

    - uses: actions/upload-artifact@v1
      name: Store Resume artifacts
      with:
        name: resume
        path: artifacts

  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest
    container:
      image: pulumi/actions
      options: --entrypoint /bin/bash

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/download-artifact@v1
      with:
        name: resume

    - name: Install pipenv
      run: python3 -m pip install pipenv

    - name: Pulumi Update
      run: |
        pipenv update
        pipenv run /usr/bin/pulumi-action up --non-interactive --suppress-outputs -s prod
      working-directory: infra
      env:
        PULUMI_CI: up

    - name: Upload files
      run: make deploy
      env:
        ARTIFACTS: /home/runner/work/resume/resume/resume
